### ISSUE TITLE
[Just aesthetic] Create GIF in README.md that is more readable

### ISSUE THREAD

**Issue by operatorequals** [eldraco/domain_analyzer#13]
Hey,
GIFs in READMEs are really cool, but this one has a lot of unused space to the right, making it little bit impossible to read.
If you crop about 1/3 of the blank space in the right edge, the GIF will be better distributed to the screen, and the letters will become readable.

That's just for demonstration purposes, and doesn't affect the application itself (of course), which, by the way, is AWESOME!

**Comment by verovaleros** [comment]
Thanks, we will attempt to re-work the GIF in the upcoming release.

**Comment by verovaleros** [comment]
This should be addressed in the last commit.
