### ISSUE TITLE
¿Que hay acerca del Disclosure?

### ISSUE THREAD

**Issue by insanitus** [eldraco/domain_analyzer#14]
¿Han considerado poner un Disclosure?

Ej,
 Este software es para uso meramente educativo, no nos hacemos responsables por el mal uso que se le de.

**Comment by eldraco** [comment]
Hi.
Thanks for your suggestion.
Well, honestly I never liked disclosures. Nobody needs that to know what it is for. And I can't stop people for using it for what they want, regardless of my intent. And the people that don't like the tool doesn't need any excuse. The license is enough for this.

**Comment by insanitus** [comment]
Ok, I see, have a nice day (n__n)
