### ISSUE TITLE
Can't connect to Google Web!

### ISSUE THREAD

**Issue by HanseSecure** [eldraco/domain_analyzer#17]
Hey,

first thanks for your great project!

My System:
Virtualbox recent Kali Rolling 64 Bit (Host: Win10 Pro 64Bit)

If use following command:
sudo domain_analyzer.py -d $target -o -e 

I always get following Error for "Searching for mynaric.com. emails in Google":
"Can't connect to Google Web!"

What do i missing or is this an general issue?

Cheers
Flo

**Comment by HanseSecure** [comment]
Inactive repo

**Comment by eldraco** [comment]
Hi HanseSecure
I couldn't reply before. 

If I use the same domain a you but without the final . then it works well for me.

sudo domain_analyzer.py -d mynaric.com -o -e

Try like that

Sebas

**Comment by HanseSecure** [comment]
works ;-)

Thanks
