### ISSUE TITLE
Python-dnspython issues 

### ISSUE THREAD

**Issue by opayemim** [eldraco/domain_analyzer#19]
Not running, says "You need to install python-dnspython. apt-get install python-dnspython" I tried installing it with apt but package not found. Downloaded and install dnspthon manually but still the same thing.

**Comment by verovaleros** [comment]
This will be solved in the upcoming code update. Stay tuned.

**Comment by verovaleros** [comment]
Please check the python2.7 branch, the docker image should have all the dependencies installed. There's also now a requirements.txt file, which should help with the installations, and if you need, check also the Dockerfile which has all the linux packages we are installing to make the old version work.
