### ISSUE TITLE
OSError, No such file or directory

### ISSUE THREAD

**Issue by guidorugo** [eldraco/domain_analyzer#2]
Fresh install. 
Ubuntu 16.04.3
Python 2.7.12

`user@user ~/D/domain_analyzer-master> sudo ./domain_analyzer.py -d website.net -o -e
+----------------------------------------------------------------------+

A lot of stuff

--------------End  Summary --------------
-----------------------------------------

<type 'exceptions.OSError'>
(2, 'No such file or directory')
[Errno 2] No such file or directory
x = 2
y = No such file or directory
`

**Comment by eldraco** [comment]
Thanks for the report. The problem was double. How to find zenmap in the system, and when we were moving the xml files to their final folder.
Can you try now and let us know?

**Comment by guidorugo** [comment]
Now is working, thanks
