### ISSUE TITLE
ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by mvella** [eldraco/domain_analyzer#8]
Just downloaded and ran domain_analyzer, playing around with different features, so far the info is great!  Thanks for the dev work!  Host is Kali Linux.

I did get the following error a couple minutes through run time of the following command:
root@--- #  ./domain_analyzer.py -d <domain>.com 

<<running through script just fine with good output>>

Checking with nmap the reverse DNS hostnames of every <ip>/24 netblock using system default resolver...
	<<good output>>

Searching for <domain>.com emails in google
	<<good output>>
	
Checking 55 active hosts using nmap... (nmap -sn -n -v -PP -PM -PS80,25 -PA -PY -PU53,40125 -PE --reason <ip> -oA <output_directory>/nmap/<ip>.sn)
	<<good output until break>>

---This is where script breaks and kicks out the following error---	
		
<type 'exceptions.ValueError'>
('No closing quotation',)
No closing quotation
<type 'exceptions.ValueError'>
('need more than 1 value to unpack',)
need more than 1 value to unpack
Traceback (most recent call last):
  File "./domain_analyzer.py", line 2837, in <module>
    main()
  File "./domain_analyzer.py", line 2765, in main
    analyze_domain(unrelated_domain)
  File "./domain_analyzer.py", line 2256, in analyze_domain
    x, y = inst          # __getitem__ allows args to be unpacked directly
ValueError: need more than 1 value to unpack
root@--- #

**Comment by eldraco** [comment]
Hi!
Thanks for trying it out.
I found several things related to this. Please check the last code and tell us how it works.
1) It seems that in your case it found some domains in the .com TLD and when trying to find related ones in robtex, we were reading the html without proper checks. Fixed.
2) In macos, the dnspython library installed from pip can not resolve the domain 'com'. Linux can>
